### PR TITLE
Fix .all() shorthand so it behaves like other shorthand calls

### PR DESCRIPTION
**Pull request by bzmw**
Fixes the .all() shorthand so that it behaves similarly to the other shorthand calls.

### CODE REVIEW

**Review by dobs — CHANGES_REQUESTED** [review]
I'd prefer exporting `all` on its own to maintain the stateless API if possible, even if just as a convenience wrapper, e.g.

```typescript
export function all(apiParameters: APIParameters) APIPromise {
  const { token, ...rest } = apiParameters
  return api({token}).all(rest)
}
```

Unless we're moving strongly toward partials? Otherwise LGTM.

**Comment by bzmw** [comment]
I'm not sure which I prefer.

Having it exported on it's own seems like an anti-pattern with the rest of the partials acting the way they do. Why have a top level object for regular api calls, and then another for `all`? Perhaps I'm missing something.

**Comment by dobs** [comment]
It's tricky. :)

Having `api` and `all` at the same level is a holdover from V1. That might not be enough reason on its own to keep that distinction.

I prefer keeping `all` separate in part because it's more "here be dragons" -- difficult to ensure consistent behaviour and might have some warts that aren't seamlessly compatible with partial application. That isn't necessarily solved by adding a top-level shortcut though.

Either way I'll drop the change request, leave it to your discretion.

**Review by dobs — APPROVED** [review]

**Comment by dobs** [comment]
On second thought, one loose end: We need to at least remove `all` as an documented export from the README.

**Pull request merged**
