### PR TITLE
Update `change` event types to allow `ChangePayload` & documentation updates

### LINKED ISSUE #336: Incorrect Type Definitions
There appears to be some disparity between type definitions and documentation as well as an incorrect parameter type for the `change` function. Documentation issues are around both the `change` function and how to add headers to normal API calls such as `POST` requests.

I will see if I can get a PR ready to resolve this.

### PR DESCRIPTION
**Pull request by parkeyparker**
The `change` function only accepted the `EventParameters` parameter type which meant that it couldn't be used to send a Change event as per the API documentation which doesn't require a severity to be passed. The `change` function now uses the `ChangeParameters` type for it's parameter and the tests have been updated/added accordingly. This will resolve #336.

Small changes made to documentation to reflect the above as well as giving an example of how to add headers to a request (related to #276). Resolved a few markdown linting issues too.

### CODE REVIEW

**Comment by parkeyparker** [comment]
Not sure who from @PagerDuty would be best to ask about the future of this project? @gempesaw would you know?

**Comment by gempesaw** [comment]
@parkeyparker hi there, unfortunately I don't know anything about this project! I did make my best guess at the team who owns it internally, and raised it with them on slack :)

**Comment by parkeyparker** [comment]
@gempesaw awesome, thank you!

**Review by tpgaviria — APPROVED** [review]
@parkeyparker This is great! Thank you for spotting these and whipping up a fix. I will merge this to main and put together a proper version release that includes this shortly.

**Comment by puglyfe** [comment]
@tpgaviria would you be able to publish these changes when you get a chance? It looks like this hasn't yet made it into a release.

**Comment by parkeyparker** [comment]
@tpgaviria any chance this can make it into a release at some point please? Currently pinning to a commit hash which isn't ideal.

**Comment by pmould** [comment]
any updates on when a new version would be released with these changes?

**Pull request merged**
